### ISSUE TITLE
How to specify \epsilon optimality (and other questions regarding usage)

### ISSUE THREAD

**Issue by ShuhuaGao** [coin-or/Couenne#50]
Thanks for the development of this excellent package. I have three problems that need your help.

1. Branch and bound algorithms can guarantee global $\epsilon$-optimality in theory. However, I did not find how to specify the tolerance parameter $\epsilon$ in Couenne's manual. There is the only **feas_tolerance** to check feasibility.  At the end, Couenne prints the "Lower bound" and the "Upper bound" as well as the "gap" between the two. How can we specify the desired gap as a termination condition?

2. In sBB algorithm of the related paper [1] (Table 1), the upper bound $z^u$ keeps reducing (at least non-increasing) in each iteration. Is it possible for Couenne to output the value of $z^u$ of each iteration?

3. (Possible bug) From the manual, we may control the print levels of `Cbc` by `mip_log_level`. However, once I put the following line into _couenne.opt_
    ```
    mip_log_level 1
    ```
      Couenne stops working and terminates instantaneously without any output. The value "1" above does not matter here; other values like "0" and "2" lead to the same result. 

Version info:
- Couenne 0.5.7 (Windows 64-bit) downloaded from [AMPL](https://ampl.com/products/solvers/open-source/).
- I used Couenne with the JuMP framework in Julia and the [AmplNLWriter.jl](https://github.com/jump-dev/AmplNLWriter.jl) interface.

[1] Belotti, Pietro, et al. "Branching and bounds tightening techniques for non-convex MINLP." Optimization Methods & Software 24.4-5 (2009): 597-634.

**Comment by ShuhuaGao** [comment]
Regarding question 3 above, the fact is that Couenne cannot recognize the option `mip_log_level`. See message below.
```
Couenne 0.5.7 -- an Open-Source solver for Mixed Integer Nonlinear Optimization
Mailing list: couenne@list.coin-or.org
Instructions: http://www.coin-or.org/Couenne
Exception of type: OPTION_INVALID in file "D:\a\1\s\Ipopt\Ipopt\src\Common\IpOptionsList.cpp" at line 639:
 Exception message: Read Option: "mip_log_level". It is not a valid option. Check the list of available options.
```

[Update] After checking the source code, the proper option name to control CBC log level is `bb_log_level`.

**Comment by merraksh** [comment]
Hello Shuhua,

 

1. the parameter, to be specified in couenne.opt, is called allowable_mip_gap, and it is a fractional number equivalent to the gap: if you want to stop when the gap is below 25%, set it to .25.

2. Couenne outputs "Integer solution of <VALUE> found ... after <T> seconds"; this does not happen at every iteration (or every BB node) because finding such a solution is computationally expensive and may not be successful at every node.

3. Indeed it is a typo in the manual. The actual name of the parameter is bb_log_level.

 

I hope this helps. Regards,

Pietro

 
 

Sent: Tuesday, December 22, 2020 at 2:01 PM

**Comment by ShuhuaGao** [comment]
Many thanks!
