### ISSUE TITLE
No solution/ Time Limit Reached Error in Couenne 

### ISSUE THREAD

**Issue by Jainendra1712** [coin-or/Couenne#54]
Dear All,
I am working on pyomo and running an optimization program on google colab (Optimizer/Solver is Couenne).
I am getting an error as:
"No Solution"
"NLP Heuristic: time limit reached"

The results I am getting are not matching with my GAMS optimization.

I already tried the option of writing "time_limit 100" in couenne.opt file. But still my code is running for less than 2 seconds.
I don't know because of what reasons I am not getting a solution.

Link for the code:
https://colab.research.google.com/drive/12G0M5NGf8BkhxYmK5jdFf5ulBbtnOG28?usp=sharing

Thank You

**Comment by tkralphs** [comment]
It looks to me like it's running for two seconds because that's how long it takes to solve to optimality. The output indicates it has found the optimum, unless I'm misinterpreting. These lines are the important ones:
```
Lower bound:                               -17240
Upper bound:                               -17240  (gap: 0.00%)
```
The lines indicating the NLP heuristic has reached its time limit are just informational and don't indicate an issue, there is just a time limit on the heuristic (but I think this time limit is 2 seconds, so it's a mystery to me how it can time out so many times within a three-second run).

**Comment by Jainendra1712** [comment]
Error was in writing the code.
